# Generated by Django 5.1 on 2024-08-17 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Категория')),
                ('color', models.CharField(choices=[('RED', 'Красный'), ('YELLOW', 'Желтый'), ('GREEN', 'Зеленый'), ('BLUE', 'Синий'), ('BLACK', 'Черный'), ('WHITE', 'Белый')], default='WHITE', max_length=10, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='todolist.category', verbose_name='Категория'),
        ),
    ]
